### ISSUE TITLE
Bloc son

### ISSUE THREAD

**Issue by MagaliAngles** [noesya/osuny#1014]
Prévoir un bloc Son dans les blocs de base

**Comment by arnaudlevy** [comment]
Ce bloc doit pouvoir jouer un mp3 uploadé (avec un joli player), ou embed un soundcloud à partir de l'URL publique

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/commit/09e3be3d82f9c99aed37e478915a59034c20687d

**Comment by arnaudlevy** [comment]
On a pas soundcloud mais oui, on peut fermer 😃
