### ISSUE TITLE
Les children des pages sont en dépendances

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1028]
Actuellement, dans `Communication::Website::Page`, on a défini les children en dépendance.

Si la raison était de gérer le fil d'ariane en cas de changement de slug, il faudrait tout simplement avoir en références les descendants car le `connect_dependencies` de la page d'accueil crée une connexion avec TOUS les objets indirects en dépendance de TOUTES les pages enfants

**Comment by arnaudlevy** [comment]
C'est effectivement une erreur, sauf pour les enfants directs si pas de bloc
