### ISSUE TITLE
Base commune fiche chercheur.e.s

### ISSUE THREAD

**Issue by MagaliAngles** [noesya/osuny#1042]
Est-il possible  d'avoir une base commune pour toutes les instances. Là sur mon site perso je rédige un article et j'aimerai rajouter un bloc personnes avec les chercheur.e.s mais il faut que je recrée des fiches pour certains qui existent déjà, c'est dommage. Autant pour les personnes administratives d'une organisation, je comprends c'est propre à l'organisation. Mais les chercheur.e.s peuvent être afilié.e.s à plusieurs universités ou intervenir ponctuellement dans une université et si on veut faire une actu sur eux, ça serait bien d'avoir accès à ces fiches ! Qu'en pensez-vous ?

**Comment by arnaudlevy** [comment]
C'est vrai que ce serait pratique pour les personnes et organisations de pouvoir les partager.
Je sais pas comment gérer, en interface et en dev.

**Comment by pabois** [comment]
Pas de bonne solution. Ce sont des sujets risqués à cause du GDPR.
On a aussi des cas où les données des personnes ne sont pas les même d'une université à l'autre.
