### ISSUE TITLE
"Pure"-ifier les vues Devise

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1068]

**Comment by arnaudlevy** [comment]
Elles le sont déjà, je comprends pas :)

**Comment by SebouChu** [comment]
Sur mon instance, la page de connexion était en mode appstack je comprends pas

**Comment by arnaudlevy** [comment]
ah oui j'ai pas bien compris pourquoi des fois oui des fois non

**Comment by arnaudlevy** [comment]
à un moment, il va falloir locker tout à pure et basta

**Comment by SebouChu** [comment]
Le fix est dans la branche headings
