### ISSUE TITLE
Pb publication de posistions des blocs

### ISSUE THREAD

**Issue by justinpuyo** [noesya/osuny#1125]
La position des blocs n'est pas toujours publiée après les avoir bougés. Obligé de faire "Modifier" > "Enregistrer" pour prendre en compte

ex. ici : https://www.iut.u-bordeaux-montaigne.fr/formation/scolarite/la-rentree-universitaire/
Le CTA "Inscription administrative". En back il est bien en haut alors qu'en front il n'est pas remonté.

**Comment by arnaudlevy** [comment]
@SebouChu pb de dépendance ?

**Comment by SebouChu** [comment]
Normalement c'est corrigé @justinpuyo !
