### ISSUE TITLE
NoMethodError in Communication::Website#rebuild_connections_and_git_files_without_delay

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1135]
## Error in Osuny

**NoMethodError** in **Communication::Website#rebuild_connections_and_git_files_without_delay**
undefined method `slug_with_ancestors' for nil:NilClass

    "/#{website.special_page(Communication::Website::Page::ResearchHalPublication, language: language).slug_with_ancestors}/:year-:slug/"
                                                                                                      ^^^^^^^^^^^^^^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/64acc7b1790a7e00088847b3?event_id=64acc7b100bee2a45a820000&i=gh&m=ci)

## Stacktrace

    app/models/communication/website/permalink/publication.rb:36 - pattern_in_website
    app/models/communication/website/permalink.rb:96 - pattern
    app/models/communication/website/permalink.rb:132 - published_path
    app/models/communication/website/permalink.rb:101 - computed_path
    app/models/communication/website/permalink.rb:107 - save_if_needed
    app/models/concerns/with_permalink.rb:29 - manage_permalink_in_website
    app/models/communication/website/git_file.rb:73 - manage_permalink
    app/models/communication/website/git_file.rb:42 - sync
    app/models/communication/website.rb:108 - block in sync_with_git
    app/models/communication/website.rb:107 - each
    app/models/communication/website.rb:107 - sync_with_git
    app/models/communication/website/with_connected_objects.rb:18 - rebuild_connections_and_git_files
    bin/bundle:113 - load
    bin/bundle:113 - <main>

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/64acc7b1790a7e00088847b3?event_id=64acc7b100bee2a45a820000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Je peux fixer en ajoutant un &, mais je comprends pas pourquoi le truc se produit @pabois @SebouChu
