### ISSUE TITLE
Problème de duplication d'une page (les blocs de contenus ne se dupliquent pas)

### ISSUE THREAD

**Issue by MagaliAngles** [noesya/osuny#1142]
J'ai dupliqué cette page
https://demo.osuny.org/admin/communication/websites/0aee4b28-85b6-463c-9395-f300fa131763/fr/pages/6ff1e074-4d5c-4ac8-957e-e5d062087ebf, que j'ai renommé "gestion des types" mais ça n'a pas dupliqué les blocs de contenus 

https://demo.osuny.org/admin/communication/websites/0aee4b28-85b6-463c-9395-f300fa131763/fr/pages/16ae4793-a419-42e1-8061-a4e933d6a6f2

**Comment by MagaliAngles** [comment]
En fait les blocs de contenus ont été dupliqués dans la page que je souhaitais dupliquer (gestion des catégories) et non pas dans la nouvelle. Et quand je supprime un bloc en doublon, j'arrive sur la page 'gestion des types" celle que j'ai dupliqué. Très bizarre.

https://github.com/noesya/osuny/assets/108729992/f60bb985-df2e-4064-8573-061621379572

**Comment by arnaudlevy** [comment]
@pabois l'algo de dupli est pété !!!

**Comment by arnaudlevy** [comment]
Merci pour le debug précis @MagaliAngles !
