### ISSUE TITLE
Barre d'action difficilement identifiable

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny#1149]
Retour d'expérience utilisateur

Sur l'interface d'administration, que ce soit pour la création d'une page ou d'un article, la barre d'action avec les boutons "créer", "enregistrer" est difficilement identifiable car, de mon point de vue, est très proche graphiquement du footer. Ce qui rend également compliqué l'identification des boutons d'actions et le fait que le bouton ne soit pas aligné avec le reste du formulaire (comme sur la capture ci dessous).

<img width="1408" alt="Capture d’écran 2023-07-13 à 12 13 17" src="https://github.com/noesya/osuny/assets/14942470/41f953e0-8d1f-4156-8263-973a5e266a1e">

Proposition 1 :
À minima aligner le bouton Enregistrer sur le bord du formulaire

Proposition 2 :
Bouger la barre d'action entre le fil d'ariane et le début du formulaire
<img width="1367" alt="Capture d’écran 2023-07-13 à 12 15 50" src="https://github.com/noesya/osuny/assets/14942470/41755ffa-eaae-453e-84bf-eb98f25bd1e1">

**Comment by arnaudlevy** [comment]
T'as raison !
On va refondre tout ça à la rentrée.
En attendant, je peux tenter un autre style.

**Comment by arnaudlevy** [comment]
<img width="1792" alt="Capture d’écran 2023-07-13 à 12 26 15" src="https://github.com/noesya/osuny/assets/2088968/d5fe03d8-4a5b-4fe4-95b7-ad34a3fbaed8">

ça te va ?

**Comment by sachaandre** [comment]
Si ca convient au reste de l'équipe, tout me va ;)
Je pense effectivement que ce sera plus lisible pour ceux qui découvriront la plateforme !

**Comment by arnaudlevy** [comment]
Ca part en prod
