### ISSUE TITLE
Bloc Chapitre : summernote n'enregistre pas le contenu en html

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#1156]
Lorsqu'on rentre du contenu en html directement, il ne s'enregistre pas.

<img width="662" alt="image" src="https://github.com/noesya/osuny/assets/4630530/73c780a4-f008-40b5-91c3-f5ed596e91ba">

**Comment by arnaudlevy** [comment]
J'ai remarqué, en fait il faut sortir de la vue code avant d'enregistrer

**Comment by arnaudlevy** [comment]
https://github.com/summernote/summernote/issues/3578

**Comment by alexisben** [comment]
Corrigé dans https://github.com/noesya/osuny/pull/1161
