### ISSUE TITLE
Suggestion : mettre le contenu complet des articles dans les flux RSS

### ISSUE THREAD

**Issue by treyssatvincent** [noesya/osuny#1164]
Quand on utilise un lecteur de flux RSS, généralement on préfère ne pas le quitter pour lire un article (du moins, c'est mon cas).

D'un point de vu sobriété, cela permet d'éviter le chargement des feuilles de styles et des scripts du site.

**Comment by arnaudlevy** [comment]
Merci !
@alexisben on peut changer ça tu crois dans Hugo ?
Il faudrait qu'on génère en back une version texte seule ?

**Comment by arnaudlevy** [comment]
@treyssatvincent j'ai cherché, en fait [la spécification RSS](https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt) indique que la description doit être un synopsis du contenu. 

D'un côté avoir le texte complet éviterait de charger le style, de l'autre ça fait des flux RSS obèses, qui ne servent plus à notifier les nouveaux contenus.

**Comment by arnaudlevy** [comment]
Il existe des outils qui font ce que tu souhaites @treyssatvincent :  
https://github.com/pictuga/morss
https://www.fivefilters.org/full-text-rss/
https://github.com/Dither/full-text-rss
