### ISSUE TITLE
Ajouter les catégories d'actualité dans le bloc de listes "Pages"

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny#1203]
Je cherche à afficher sur ma page "Actualités" et sur ma page "Accueil" les 3 catégories d'actualités sous forme de blocs, comme le propose le bloc liste "Pages". Or dans la sélections de pages je n'arrive pas à accéder aux pages qui correspondent à mes 3 catégories ( pages comme celle ci : https://inspiring-druid-48e192.netlify.app/actualites/communiques/ )

<img width="482" alt="Capture d’écran 2023-08-15 à 15 48 19" src="https://github.com/noesya/osuny/assets/14942470/3921ae2f-223c-4533-9b24-e01a19470605">

**Comment by arnaudlevy** [comment]
Ca soulève pas mal de questions de fond d'ergonomie (@Violenn) et d'architecture (@pabois @SebouChu)

**Comment by arnaudlevy** [comment]
On va attaquer une importante refonte ergonomique en septembre, on traitera peut-être ce point :)
En attendant, le bloc "actualités" permet de lister les n dernières actualités d'une catégorie.
Ce n'est pas exactement la même chose, mais c'est pratique.

**Comment by sachaandre** [comment]
Je vais prendre cette solution en attendant ! Merci pour l'information
