### ISSUE TITLE
Pas de possibilité d'upload des webp

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny#1204]
Pour des images d'articles ou de page je ne peux pas uploads des webp.

Est ce qu'il est prévu de pouvoir en upload ?

**Comment by arnaudlevy** [comment]
Non, c'est dans l'autre sens : tu upload des jpg ou png, et on génère les webp.
Tu as une source en webp ?

**Comment by sachaandre** [comment]
Oui j'avais une source en webp, mais je l'ai converti en jpg 🤷

**Comment by arnaudlevy** [comment]
@pabois @SebouChu est-ce qu'on devrait autoriser les webp en upload back ? 
Et peut-être les convertir directement en png ou jpg ?

**Comment by pabois** [comment]
Ca n'est pas pareil partout. Certains champs n'ont pas de contrainte (les fichiers par exemple).
Le thème a une mécanique qui prend l'image (jpg, png) et en fait des formats divers. Si on envoie un webp ça ne pourra pas s'afficher sur les anciens navigateurs.
Faut-il à l'upload forcer la conversion en png ?

**Comment by arnaudlevy** [comment]
On ne traite pas, tant que le sujet n'est pas plus problématique
