### ISSUE TITLE
Octokit::InvalidRepository in Communication::Website#update_theme_version_without_delay

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1216]
## Error in Osuny

**Octokit::InvalidRepository** in **Communication::Website#update_theme_version_without_delay**
"" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64e71bc300beb7e5ef640000&i=gh&m=ci)

## Stacktrace

    app/services/git/providers/github.rb:97 - default_branch
    app/services/git/providers/github.rb:101 - branch_sha
    app/services/git/providers/github.rb:128 - tree
    app/services/git/providers/github.rb:115 - tree_items_by_path
    app/services/git/providers/github.rb:109 - tree_item_at_path
    app/services/git/providers/github.rb:78 - git_sha
    app/services/git/providers/github.rb:48 - update_theme
    app/services/git/repository.rb:30 - update_theme_version!
    app/models/communication/website/with_git_repository.rb:53 - update_theme_version
    bin/bundle:113 - load
    bin/bundle:113 - <main>

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64e71bc300beb7e5ef640000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/commit/2ab22dd7a91b4f8d445d7de43f29b549b6c5a38c

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::InvalidRepository** in **Communication::Website#update_theme_version_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64e71c3700bed589498d0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::InvalidRepository** in **Communication::Website#update_theme_version_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64e71cba00beb9f9c46f0000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::InvalidRepository** in **Communication::Website#update_theme_version_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64e71cd300bec1a357af0000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::InvalidRepository** in **Communication::Website#update_theme_version_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64e71cd300bec1a357af0000&i=gh&m=fx)

**Comment by SebouChu** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::InvalidRepository** in **Communication::Website::Menu#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64edf3a900bee0aa6ea80000&i=gh&m=ra)

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Octokit::InvalidRepository** in **Communication::Website::Menu#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/64e71bc356f3b000081b601b?event_id=64edf3b100bee0aa795a0000&i=gh&m=fx)
