### ISSUE TITLE
Problème de lien

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1282]
https://reboot.osuny.org/admin/university/people/2c56d39b-ef71-4a31-88ac-dc2ae26203f3

Mathieu est lié à la page https://reboot.osuny.org/admin/communication/websites/5d215dc1-12be-4df5-99d4-dfd2a1100090/d193978f-0f3c-431e-b1b9-5e544ec28ed5/pages/9a334241-76dd-4785-b49f-2cbd8125f232

pourtant, non

**Comment by SebouChu** [comment]
La personne étant présente via sa connexion à la page Equipe (et 16h30), on ne supprime pas la mauvaise connexion car l'objet est encore en dépendance du website

**Comment by arnaudlevy** [comment]
mais quelle est la logique de ne pas supprimer la connexion qui n'est plus valable ?

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/pull/1313
