### ISSUE TITLE
Problème de CSP avec Vimeo

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny#1312]
Sur [Futurs](https://futurs-site.web.deuxfleurs.fr/), Vimeo est bloqué par les CSP : 

`Refused to frame 'https://player.vimeo.com/' because it violates the following Content Security Policy directive: "default-src 'self' osuny-1b4da.kxcdn.com *.osuny.org osuny.s3.fr-par.scw.cloud tile.openstreetmap.org www.youtube.com". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.`

[website.yml](https://github.com/noesya/futurs-site/blob/main/data/website.yml) ne se met pas à jour (alors que ça avait bien ajouté Youtube) ni lorsque l'on change l'url d'un bloc vidéo, ni lorsqu'on en créé un nouveau.

**Comment by arnaudlevy** [comment]
il faut réenregistrer le site web

**Comment by arnaudlevy** [comment]
ça fonctionne mal

**Comment by arnaudlevy** [comment]
:/
