### ISSUE TITLE
Le cadrage photo est cassé

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1343]
https://reboot.osuny.org/admin/university/people/70a8e07c-3aaf-41a7-853e-e677b9041b77

J'ai cadré correctement avec le cropper et j'ai obtenu ça :

<img width="444" alt="Capture d’écran 2023-10-17 à 09 27 16" src="https://github.com/noesya/osuny/assets/2088968/17213280-6669-491d-a8de-8a8bb8ff91bd">

**Comment by arnaudlevy** [comment]
En le refaisant, ça fonctionne.
Peut-être est-ce différent au create de la personne et au save ?

**Comment by pabois** [comment]
ça ne devrait pas

**Comment by arnaudlevy** [comment]
Et ?

**Comment by pabois** [comment]
Je ne reproduis pas, ni à la création ni à l'update :(

**Comment by pabois** [comment]
Je close
