### ISSUE TITLE
Administration Site Web - Fonction de paramètre non intuitive

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny#1368]
Petite question après avoir scrollé sur la page de modification de mon site,
À quoi sert cette partie ? Est-ce pour le logo ?

<img width="448" alt="Capture d’écran 2023-10-29 à 23 09 34" src="https://github.com/noesya/osuny/assets/14942470/8a6af407-c538-4420-abcc-0ecea32433ad">

**Comment by arnaudlevy** [comment]
Ajouter le texte : 
_Cela sera utilisée dans les pages et actualités qui n'ont pas d'image, si le thème est paramétré pour afficher des images dans tous les cas. C'est aussi l'image de partage par défaut._

**Comment by arnaudlevy** [comment]
@sachaandre c'est ajouté, et j'ai rangé l'écran, dis-moi ton avis !

**Comment by arnaudlevy** [comment]
Est-ce plus clair : 
_L'image par défaut sera utilisée dans les pages et actualités qui n'ont pas d'image, si le thème est paramétré pour utiliser les images par défaut. C'est aussi l'image de partage par défaut._

**Comment by arnaudlevy** [comment]
Il n'y a qu'un thème mais il a des paramètres  
https://developers.osuny.org/docs/website/configurer-le-site/
