### ISSUE TITLE
NoMethodError in admin/communication/extranets#update

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1403]
## Error in Osuny

**NoMethodError** in **admin/communication/extranets#update**
undefined method `empty?' for nil:NilClass

      return @template.dup if @template.empty?
                                       ^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/654bda6eed57a10008395427?event_id=654bda6e00c90c529f4c0000&i=gh&m=ci)

## Stacktrace

    app/models/communication/extranet/with_style.rb:12 - generate_css
    app/controllers/admin/communication/extranets_controller.rb:38 - update
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/654bda6eed57a10008395427?event_id=654bda6e00c90c529f4c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Pentest
