### ISSUE TITLE
Block data "position" key issue 

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#1404]
L'ordre des positions n'est plus respecté, ou ne suit pas une logique correct pour le thème :

https://github.com/noesya/osuny-example/blob/main/content/fr/pages/blocks/blocs-de-liste/actualites-1/_index.html

Il faut qu'on échange sur l'utilité de la clé "position" en back vs en front.

**Comment by arnaudlevy** [comment]
c'est pas parce que les positions repartent à 0 après un heading?

**Comment by alexisben** [comment]
Ok en fait on s'en sert pas du tout en front, c'est du legacy

**Comment by arnaudlevy** [comment]
c'est vrai ?
Je peux virer ?

**Comment by arnaudlevy** [comment]
je l'ai dans : 
- categories
- pages
- programs

**Comment by alexisben** [comment]
Attention je ne parle que des blocks !

**Comment by arnaudlevy** [comment]
ah
je ne touche à rien ;)
