### ISSUE TITLE
Ce serait chouette de pouvoir changer la langue par défaut d'un site

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1410]
https://idn.osuny.org/admin/communication/websites/5ff011e4-e87f-451f-8d20-93d22bf7fc83

Il faudrait le mettre en anglais

**Comment by pabois** [comment]
Pour faire ça il faudrait, au moment du switch de langue par défaut, qu'on regarde tout les contenus existants du site, qu'on vérifie qu'il en existe bien une version dans la nouvelle langue et si ce n'est pas le cas la créer, puis inverser la relation entre les éléments traduits et le "master" (original_id). 
Par exemple on switch du français vers l'anglais. On prend tous les contenus, on vérifie qu'il en existe bien une version anglaise, et sinon on force la création. Ensuite chaque élément anglais a un original_id vers le français, et chaque élément français n'a pas de original_id. On doit donc update le original_id de chaque élément français en lui mettant l'id de sa traduction anglaise. On doit aussi, s'il y a d'autres langues, modifier le original_id de chaque traduction pour pointer vers l'original anglais et plus le français. Et enfin vider le original_id de tous les éléments anglais.

**Comment by pabois** [comment]
C'est trop compliqué à développer pour un usage à mon sens inutile.
Si on se "trompe" sur la langue par défaut du site web on recréé le site web !
Je close l'issue
