### ISSUE TITLE
Problème à la création d'un site

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1426]
https://github.com/noesya/lcdc-site/commit/30e68ae74cafb72ee831874d63aaf6941e3642c2

Le commit n'est pas rattaché à la branche `main`, il flotte.

**Comment by arnaudlevy** [comment]
Investigation pour Sherlock Holmes !

**Comment by arnaudlevy** [comment]
https://github.com/noesya/lcdc-site/commit/9b849905852d7d4ffd6cf314e0a5b1f1550deef8

J'ai fait un fix manuel mais je ne comprends pas.

**Comment by SebouChu** [comment]
Il semblerait que @arnaudlevy ait corrigé tout seul dans https://github.com/noesya/osuny/commit/db547a38a673579f2eafc7b68e5ee412a73f4f41

A voir dans le futur si ça se reproduit
