### ISSUE TITLE
Demande d'un bouton pour actualiser les versions de tous les sites dans l'espace serveur

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#1450]
Ça serait trop génial d'avoir un bouton qui actualise toutes les versions des sites dans server/websites <3 

<img width="1356" alt="image" src="https://github.com/noesya/osuny/assets/4630530/5639c956-54fd-44c6-ad64-5afd03eae27f">

**Comment by arnaudlevy** [comment]
mais c'est peut-être plus pratique d'avoir un bouton ?
