### ISSUE TITLE
Wishlist - Integration Unsplash pour Image d'article / page

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny#1497]
Je ne sais pas si cette idée a été évoquée, mais serait-il possible d'ajouter un module permettant d'ajouter une image d'une banque d'image CC comme Unsplash pour pouvoir illustrer des articles ?

<img width="344" alt="Capture d’écran 2023-12-16 à 00 01 54" src="https://github.com/noesya/osuny/assets/14942470/bd6d544b-4520-4637-9ee8-7cd906673dcd">

**Comment by arnaudlevy** [comment]
C'est déjà le cas, le bouton rechercher est un peu plus bas

**Comment by sachaandre** [comment]
Effectivement, j'ai pas mis mes yeux en face des trous, mes excuses !
