### ISSUE TITLE
Avoir une phrase par défaut quand il n'y a pas d'évènements en cours / à venir

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny#1499]
Dans ma page d'accueil, j'ai un bloc "Agenda" avec les 3 prochains évènements en cours / à venir.
N'ayant pas d'évènements prévus à l'agenda, j'ai un bloc vide laissant place à un titre, puis un vide, puis la prochaine section.

Est il possible d'avoir dans le bloc une phrase par défaut pour indiquer qu'il n'y a pas d'évènement ?
Et / ou laisser la possibilité dans les options du bloc d'indiquer soit même une phrase lorsque le bloc est vide ? 

<img width="1072" alt="Capture d’écran 2023-12-16 à 13 27 00" src="https://github.com/noesya/osuny/assets/14942470/7b928ac2-b0d4-4809-8505-91fe5ebb3ed8">

**Comment by arnaudlevy** [comment]
@sachaandre si tu mets une phrase elle apparaît, si tu n'en mets pas, s'il n'y a pas d'événement le bloc disparaît
