### ISSUE TITLE
Améliorer l'export github des pages et des posts

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#15]
# Pages

- [x] créer des dossiers avec l'arbo
- [x] déplacer en cas de renommage
- [x] supprimer en cas de suppression

# Posts

- [x] créer des dossiers années / mois ou juste années
- [x] utiliser le vrai slug pour le nom de fichier, pas l'uuid
- [x] déplacer en cas de changement de slug ou de changement de date
- [x] supprimer en cas de suppression

**Comment by pabois** [comment]
Et par extension gérer la suppression de tous les types d'objets envoyés (comme un program)
