### ISSUE TITLE
Problème d'information dans le toc

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny#1501]
Dans les papers, le toc est présent dans des cas où il ne devrait pas l'être, comme sur [Degrowth](https://www.degrowthjournal.org/publications/2023-05-03-editorial/) :

![Capture d’écran 2023-12-18 à 15 54 59](https://github.com/noesya/osuny/assets/91660674/8db24175-96c4-4f82-8419-46a55a76743f)
(Ici le toc est vide car même s'il y a des blocs, aucun n'est de type heading).

On a pourtant l'info :

```
toc:
    present: true
```

**Comment by arnaudlevy** [comment]
Effectivement, il était locké, je ne sais plus pourquoi.
