### ISSUE TITLE
ActionView::Template::Error in Communication::Website::Agenda::Event#sync_with_git_without_delay

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1512]
## Error in Osuny

**ActionView::Template::Error** in **Communication::Website::Agenda::Event#sync_with_git_without_delay**
undefined method `cal' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/658c673ae2fdcb0008ef037d?event_id=658c673a00cf3d6caa2c0000&i=gh&m=ci)

## Stacktrace

    app/views/admin/communication/websites/agenda/events/_dates_static.html.erb:29 - _app_views_admin_communication_websites_agenda_events__dates_static_html_erb__3692999111319551751_3717280
    app/views/admin/communication/websites/agenda/events/static.html.erb:4 - _app_views_admin_communication_websites_agenda_events_static_html_erb___396745801256952030_3717260
    app/services/static.rb:23 - render
    app/models/communication/website/git_file.rb:66 - to_s
    app/services/git/analyzer.rb:52 - computed_sha
    app/services/git/analyzer.rb:23 - should_update?
    app/services/git/repository.rb:76 - block in sync_git_files
    app/services/git/repository.rb:71 - each
    app/services/git/repository.rb:71 - sync_git_files
    app/services/git/repository.rb:25 - sync!
    app/models/concerns/with_git.rb:37 - sync_with_git
    bin/bundle:113 - load
    bin/bundle:113 - <main>

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/658c673ae2fdcb0008ef037d?event_id=658c673a00cf3d6caa2c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SebouChu** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActionView::Template::Error** in **Communication::Website::Agenda::Event#sync_with_git_without_delay**](https://app.bugsnag.com/noesya-1/osuny/errors/658c673ae2fdcb0008ef037d?event_id=658c703700cf4b3cb54a0000&i=gh&m=fx)

**Comment by arnaudlevy** [comment]
Merci @SebouChu !
