### ISSUE TITLE
Désactiver annotate sur les sous-classes STI

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#1524]
Il faut peut-être ajuster l'option `exclude_sti_subclasses` d'Annotate pour éviter d'avoir la description dans les sous-classes telles que `Communication::Website::Configs::DevelopmentConfig`, etc etc

**Comment by arnaudlevy** [comment]
A mon avis c'est pas un pb d'avoir l'annotation partout, mais il y a peut-être des effets négatifs que je ne vois pas.

**Comment by SebouChu** [comment]
Faciliter les relectures des PRs car les annotate font du bruit quand on met à jour quelque chose sur le modèle Communication::Website::Page par exemple
