### ISSUE TITLE
Pb d'upload sur FF

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1536]
![Capture](https://github.com/noesya/osuny/assets/2088968/db5643dc-57e5-4691-a0c3-83a1b413c45a)
![Visuel-ACF-Site](https://github.com/noesya/osuny/assets/2088968/c69022f7-b7f2-44d6-a5a4-5f91f3df7052)

**Comment by SebouChu** [comment]
Problème de proxy entreprise qui n'autorisait pas les requêtes
