### ISSUE TITLE
Erreur 500 : blocs sur pages diplomes ou formations

### ISSUE THREAD

**Issue by justinpuyo** [noesya/osuny#1552]
Impossible d'ajouter ou de modifier un bloc de contenu sur une page diplôme ou formation.
J'ai une erreur 500.
ex : Bloc fichier sur page [BUT](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/bachelor-universitaire-de-technologie/)

**Comment by justinpuyo** [comment]
En fait c'est vraiment l'édition qui est impossible.
Quand j'ajoute un bloc il est bien ajouté mais vide.

**Comment by arnaudlevy** [comment]
Je regarde !
