### ISSUE TITLE
Comportement incorrect du fil d'ariane

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#1571]
Retour de Thibaut, La Criée : 
_Dans l'interface pour compléter une page, il y a le champ "Titre" puis "Nom affiché dans le fil d'ariane". Nous nous sommes rendu compte que si la page sur laquelle nous sommes est le niveau le plus bas, alors c'est le titre qui apparait. Si cette page est un niveau intermédiaire, alors c'est son nom fil d'ariane. Exemple : pour une page qui porterait le titre "La médiation à la Criée" et le nom fil d'ariane "Médiation", alors si je suis sur cette page, le fil d'ariane indiquera "La Criée > La médiation à la Criée" et si je suis dans une page enfant de cette dernière le fil d'ariane affichera " La Criée > Médiation > page enfant". Pouvons-nous remédier à ça ?_

**Comment by SebouChu** [comment]
Fixed by #1574
