### ISSUE TITLE
Améliorer les commits

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#16]
- [x] faire des commits avec fichiers multiples
- [ ] ajouter l'auteur dans le texte du commit
- [x] faire les fichiers temporaires dans un dossier pour le site (là tous les sites sont dans tmp/jekyll)

**Comment by pabois** [comment]
Le nom de l'utilisateur est de l'ordre du RGPD, je préfère ne pas le faire pour le moment
