### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny#164]
_wip_ 

Meta
- [ ] Title
- [x] Description

Facebook
- [ ] Title
- [ ] Type
- [ ] Description
- [ ] Image
- [ ] Locale
- [ ] URL

Twitter
- [ ] Title
- [ ] Description
- [ ] Image
- [ ] Site
- [ ] Author

**Comment by pabois** [comment]
Le svg n'est pas toléré par Twitter, il faut des messages pour dire que si svg, l'image de partage est souhaitable
