### ISSUE TITLE
Suggestion de Slug

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny#181]
si l'on change de title, proposer un changement de slug cf shopify (au clic sur un des textes en jaune ça ajoute dans la case slug)

<img width="589" alt="slug" src="https://user-images.githubusercontent.com/4457294/153448652-dcd3bfba-3897-46e6-abb3-a5c1ff0dae44.png">

**Comment by arnaudlevy** [comment]
Attention si on fait ça, il faudrait gérer les 301 aussi

**Comment by pabois** [comment]
duplicate #522
