### ISSUE TITLE
Mots clés

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny#182]
Ne serait-ce pas mieux d'avoir un usage de ce type pour les mots clés qu'un simple champ textearea ?

<img width="442" alt="tags" src="https://user-images.githubusercontent.com/4457294/153453367-9c7a5d6f-2356-4bc9-a322-e1eb72356a4f.png">

**Comment by arnaudlevy** [comment]
Tu veux dire à quel endroit ? Si tu parles des articles de revues scientifiques, j'ai vu des publications avec un simple champ, et d'autres avec des vrais objets cliquables. Je crois que des objets seraient peut-être mieux, pas sûr.

**Comment by pabois** [comment]
duplicate #522
