### ISSUE TITLE
Améliorer la structure

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#183]
- [ ] ajouter la home des catégories (communication_categories_path, avec path /actualites/categories et titre "Catégories" par défaut
- [ ] utiliser dans communication/website/menu/item.rb#target_for_new_category
- [ ] améliorer la gestion de la structure pour le site, pas en after create mais en after save, avec réparation

**Comment by pabois** [comment]
duplicate #187 
On ne fait pas d'index des catégories
