### ISSUE TITLE
Améliorer summernote

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#202]
- [x] Dans Hugo, vérifier la présence sur plainify et pas sur html brut
- [x] Dans Osuny, filtrer les balises au copier-coller

**Comment by sebousan** [comment]
Le partial pourrait ressembler à ça

```
{{ $content := .Content | plainify }}
{{ $content = trim $content "\n" }}
{{ if $content }}
  {{- partial "PrepareHTML" .Content -}}
{{ end }}
```
par contre j'aimerai rajouter du html pour wrapper `{{- partial "PrepareHTML" .Content -}}`

**Comment by arnaudlevy** [comment]
@pabois @sebousan j'ai des <b style="font-size:0.825rem;"> dans l'html généré par summernote :/

**Comment by arnaudlevy** [comment]
Et parfois j'ai un p, parfois j'ai rien

**Comment by arnaudlevy** [comment]
@sebousan tu as une url d'exemple ? Je cherche un cas à réparer
