### ISSUE TITLE
Faut-il un modèle pour les partenaires ?

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#227]
Les partenaires sont actuellement des données faiblement typées dans les blocs.
Ne serait-il pas logique de les matérialiser dans la partie communication, et de les utiliser ensuite comme les personnes dans le bloc organigramme ?
Si les partenaires sont utilisés plusieurs fois, c'est mieux, ça permet de mettre à jour une URL ou un logo de façon centralisée.

En même temps ça aurait du sens de limiter les partenaires au site Web, dans le cas d'une Université ce n'est pas forcément souhaitable de lister tous les partenaires de toutes les composantes. 

On fait quoi ?

**Comment by pabois** [comment]
On a un cas de répétition déjà ? Il me semble que si ça doit être scopé à un site en particulier on peut laisser de la donnée faiblement typée

**Comment by arnaudlevy** [comment]
Je crois qu'on a une piste très bien avec les alumni, je te raconte lundi
