### ISSUE TITLE
Pb de slug

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#231]
https://demo.osuny.org/admin/communication/websites/1a601e73-61f5-4c97-849f-7e8d56184c6c/pages/9190e1f0-fc5e-4e65-9efa-fa760a18bf2e

Le slug prend un -1 à la fin, donc je pense que l'analyse d'unicité a un pb de scope @pabois

**Comment by pabois** [comment]
C'est à cause de la blacklist de slugs qui l'empêche d'avoir offre-de-formation (utilisée dans les static pages)

**Comment by pabois** [comment]
Théoriquement on peut tolérer à ce niveau un slug conflictuel, mais que se passe-t-il après si on bouge la page ?
Je pense qu'il est plus sain de laisser comme ça

**Comment by arnaudlevy** [comment]
Ok compris !
