### ISSUE TITLE
Créer un champ sur les personnes pour le résumé court

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#250]
Là on utilise la description, mais c'est pas sain.
Il faudrait un string qui permet d'écrire la description utilisée sur l'index, et dans Hugo si pas rempli on prend autre chose (la desc SEO ? un summary du .Content ?)

**Comment by arnaudlevy** [comment]
https://www.osuny.org/passer-a-laction/reseau/

Là, il faudrait "Nouvelle-Aquitaine", "Grand Est", etc

**Comment by sebousan** [comment]
j'ai ajouté un champ description_short
si pas remplit ça truncate .Content
