### ISSUE TITLE
Améliorer les formations

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#255]
- [x] Ajouter un champ présentation (summernote) au début
- [x] Suivre l'ordre du front en back
- [x] Ajouter "Informations essentielles" cf Justin (voir com PA)
  - [x] Back + static (`program.main_information`)
  - [x] Hugo

**Comment by arnaudlevy** [comment]
https://bordeauxmontaigne-iut.netlify.app/offre-de-formation/bachelor-universitaire-de-technologie/metiers-du-multimedia-et-de-l-internet/

<img width="438" alt="Capture d’écran 2022-03-10 à 17 24 21" src="https://user-images.githubusercontent.com/2088968/157708756-d5fa5f2d-6ff2-4ddc-9f16-0f0c0ee29ce5.png">

**Comment by pabois** [comment]
Justin souhaitait avoir dans les pages la possibilité d'un texte assez simple en colonne de gauche, sous la TOC https://bordeauxmontaigne-iut.netlify.app/notre-institut/presentation-de-liut/

**Comment by SebouChu** [comment]
@sebousan @alexisben plus qu'à afficher le `program.main_information` sous la TOC, je vous laisse voir qui veut se lancer ;)
