### ISSUE TITLE
Bloc actualités

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#261]
- [x] Ajouter un bloc actualité
- [x] Choisir la catégorie éventuelle
- [x] Choisir le nombre d'actus
- [x] Migrer les connexions pages / actus (pour les pages déjà liées à une catégorie, créer à la migration un bloc qui reprend la liaison)

**Comment by pabois** [comment]
Il y a 39 pages avec des catégories liées : 
["88f3736c-d2d0-4ecc-85bf-d44dad542caa", "b80581df-5978-4da7-b0df-5d92726b2b8f", "5382775e-4f85-441c-9bab-385571d0189a", "4086f72b-50fe-41c0-9a7d-5946af3d027b", "e47f1bc8-3e04-4a25-b873-1c2dfd2b9f44", "a04979e4-f1fe-4891-b816-954051c53ab6", "9bde8807-2911-4254-8575-47d294c38eba", "5a71f862-15e6-4713-aa8a-6af87bf02d10", "3a84975b-6a2b-404f-8a4c-b00ba9e02900", "99bf9f36-9a42-4c4c-a86a-9579f6add9e0", "aa334ae0-da28-41eb-a3e6-3c9a94dc3687", "f9c2db5c-f7b7-46f0-aec1-7434daf88457", "162d27c2-7201-4b9e-84c5-9f4a92148e30", "3d6073e5-5aab-4997-9257-39ab046f230b", "07e036fa-9d12-4dac-a70b-593cabf17a68", "aa9fb651-f1f4-4509-a40f-ad6029b5c1fd", "4f3b280a-5426-418b-bcef-dfa396031c12", "de51f60b-d1ea-46b4-a99c-369ae97c4a2f", "d8c28358-8424-4865-90ad-af76f78434d8", "24374921-2f75-4820-95fb-84c7e90ed973", "bbfe3e19-1ef7-45ae-aa75-5b2862c1b409", "50a21a43-83aa-46f6-84c1-f7e10bfee768", "dbe7b333-b409-43b9-aebd-7405e99cc0cf", "02d5b2f1-f44a-4359-9284-5509a5bde329", "5452b61b-3059-4dd6-b540-075b05f13389", "5c6b8b51-0593-486d-bbd4-05c4cfe6d333", "b3ebd168-b79b-4dc9-83ce-6c79d098c0e2", "1c219e0b-256a-4443-a55c-e4c629103e4c", "3c5397d5-bffb-4b94-89e0-0b8e43169dd5", "aba5aca4-0f58-4577-960d-4b60a773fdc2", "7e64ea44-c432-4ac1-9689-8e0fd64cfb74", "21dac9d8-183c-4a98-98fc-0cf19704d67a", "e86b9b40-6485-4fd0-8573-5510f3622ee1", "cb30ff51-a4b0-4f37-a339-16bf4b8b1d4d", "6799c78e-2514-456e-9959-dac3afd8b5f8", "bedc5d5a-71ec-4010-acde-5c33674be5c7", "00735724-8b20-4aa7-948f-551449eb4c35", "d37011ce-866e-4dcb-ae7e-441671fab532", "cdb55639-cd53-4e5d-91d9-b1ca27ffe554"]

**Comment by pabois** [comment]
### Classcode : 
["5452b61b-3059-4dd6-b540-075b05f13389", "dbe7b333-b409-43b9-aebd-7405e99cc0cf", "3d6073e5-5aab-4997-9257-39ab046f230b", "3a84975b-6a2b-404f-8a4c-b00ba9e02900", "07e036fa-9d12-4dac-a70b-593cabf17a68", "6799c78e-2514-456e-9959-dac3afd8b5f8", "d37011ce-866e-4dcb-ae7e-441671fab532", "bedc5d5a-71ec-4010-acde-5c33674be5c7", "cdb55639-cd53-4e5d-91d9-b1ca27ffe554", "162d27c2-7201-4b9e-84c5-9f4a92148e30", "99bf9f36-9a42-4c4c-a86a-9579f6add9e0", "88f3736c-d2d0-4ecc-85bf-d44dad542caa", "5a71f862-15e6-4713-aa8a-6af87bf02d10", "00735724-8b20-4aa7-948f-551449eb4c35", "b80581df-5978-4da7-b0df-5d92726b2b8f", "5c6b8b51-0593-486d-bbd4-05c4cfe6d333", "4086f72b-50fe-41c0-9a7d-5946af3d027b", "aa334ae0-da28-41eb-a3e6-3c9a94dc3687", "e47f1bc8-3e04-4a25-b873-1c2dfd2b9f44", "02d5b2f1-f44a-4359-9284-5509a5bde329", "f9c2db5c-f7b7-46f0-aec1-7434daf88457", "aa9fb651-f1f4-4509-a40f-ad6029b5c1fd"]

### CoDé :
["5382775e-4f85-441c-9bab-385571d0189a", "cb30ff51-a4b0-4f37-a339-16bf4b8b1d4d", "50a21a43-83aa-46f6-84c1-f7e10bfee768", "21dac9d8-183c-4a98-98fc-0cf19704d67a", "a04979e4-f1fe-4891-b816-954051c53ab6", "e86b9b40-6485-4fd0-8573-5510f3622ee1", "9bde8807-2911-4254-8575-47d294c38eba"]

### BordeauxMontaigne :
["4f3b280a-5426-418b-bcef-dfa396031c12", "de51f60b-d1ea-46b4-a99c-369ae97c4a2f", "1c219e0b-256a-4443-a55c-e4c629103e4c", "3c5397d5-bffb-4b94-89e0-0b8e43169dd5", "d8c28358-8424-4865-90ad-af76f78434d8", "aba5aca4-0f58-4577-960d-4b60a773fdc2", "24374921-2f75-4820-95fb-84c7e90ed973", "7e64ea44-c432-4ac1-9689-8e0fd64cfb74", "bbfe3e19-1ef7-45ae-aa75-5b2862c1b409"]

### Demo :
["b3ebd168-b79b-4dc9-83ce-6c79d098c0e2"]
