### ISSUE TITLE
Ajouter un champ infos additionnelles

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#262]
Avec un wysiwyg simple (pas de titres, listes, liens) qui va dans la colonne de gauche

**Comment by pabois** [comment]
@arnaudlevy c'est brillant comme issue... on ne sait pas à quoi il faut l'ajouter :)

**Comment by arnaudlevy** [comment]
ha ha ha mince je sais plus du tout le contexte...

**Comment by arnaudlevy** [comment]
Ok c'était le 14 mars suite à un point IUT

**Comment by arnaudlevy** [comment]
Ah ça y est, Justin souhaitait avoir dans les pages la possibilité d'un texte assez simple en colonne de gauche, sous la TOC https://bordeauxmontaigne-iut.netlify.app/notre-institut/presentation-de-liut/
