### ISSUE TITLE
Implémenter une API CDM-fr

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#268]
http://cdm-fr.ens-lyon.fr/pdf/cdm-traductionpresentation.pdf

**Comment by arnaudlevy** [comment]
La norme a l'air à l'abandon, plein de liens morts (je vois des liens qui sont morts)

**Comment by pabois** [comment]
DOnc on va p-e pas faire cette implémentation, si ? @arnaudlevy
