### ISSUE TITLE
Faut-il cleaner les targets possibles d'un menu item maintenant que les différents index sont des pages ?

### ISSUE THREAD

**Issue by pabois** [noesya/osuny#294]

**Comment by arnaudlevy** [comment]
Oui, je pense.

**Comment by arnaudlevy** [comment]
Enfin il faut supprimer les index, puisqu'on les attribue avec le choix "page spécifique"

**Comment by pabois** [comment]
En fait je ne sais pas. C'est assez pratique d'avoir un bouton directement, genre un shortcut vers la "page spécifique" "liste des actualités"

**Comment by arnaudlevy** [comment]
C'est vrai aussi.
