### ISSUE TITLE
Page d'index : afficher l'information du type d'index pour les pages d'index dans l'admin

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#309]
Préciser dans l'admin d'une page, que la page sert à lister telle catégorie de modèle si c'est une page d'index

**Comment by arnaudlevy** [comment]
Et peut-être le faire à la place des blocs, en fonction des pages.

**Comment by pabois** [comment]
Je comprends pas le commentaire d'@arnaudlevy

**Comment by arnaudlevy** [comment]
Je veux dire que si une page est un index des posts, il faut enlever les blocs

**Comment by arnaudlevy** [comment]
@pabois

**Comment by arnaudlevy** [comment]
https://bordeauxmontaigne.osuny.org/admin/communication/websites/7cfe43ca-55cf-4b9f-af73-4186075a5034/pages/a7a72fda-cfd7-4b51-893f-1297ab8927f9

**Comment by arnaudlevy** [comment]
Comment on gère les blocs là ?

**Comment by pabois** [comment]
Après discussion : on ne veut pas supprimer les posts pour les pages : par exemple sur la page "mentions légales".
Par contre il faut gérer les blocks sur les index type index des actus
