### ISSUE TITLE
[bug]: une organization ne remonte pas quand elle est assignée à un block

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#310]
Exemple pour demo.osuny.org et la formation "Éco-conception de service numérique" (pas d'organizations dans le content du site)

**Comment by alexisben** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/4630530/163120240-2e607516-0793-464c-80fd-da63b4abe583.png">

**Comment by SebouChu** [comment]
duplicate #248
