### ISSUE TITLE
[Discussion] Grouper les onglets Catégories et Auteurs sous Actualités

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#333]
Faut-il grouper les catégories et auteurs sous/dans l'onglet Actualités pour éviter une incompréhension des utilisateurs ?

<img width="283" alt="image" src="https://user-images.githubusercontent.com/4630530/165044657-6e2d5299-77b7-42f0-9ee4-e96c769b40f6.png">

**Comment by pabois** [comment]
Je pense pas pour ma part

**Comment by arnaudlevy** [comment]
J'ai fait un truc
