### ISSUE TITLE
Mise à jour des data lors de la suppression d'un bloc

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#338]
J'ai l'impression que les statics ne sont pas mis à jour lors de la suppression d'un bloc sur une page.

**Comment by pabois** [comment]
Et problème lors de l'edit ?

**Comment by alexisben** [comment]
Je modifie et enregistre la quantité d'articles mais pas de commit côté Osuny 

https://communicationdemocratie.osuny.org/admin/communication/blocks/2e0e51ea-2520-4e26-9d2e-efe2738a373c/edit?website_id=2c9c1ff8-23a1-456e-9870-16ce3d9fd940

<img width="597" alt="image" src="https://user-images.githubusercontent.com/4630530/165733501-6659775d-a2d4-460a-b4f7-d5564d9fcf59.png">
