### ISSUE TITLE
Dénormaliser la recherche

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#339]
https://github.com/noesya/osuny/blob/27e8ced8868f4c3ee9ed5072f9cb142465fab430/app/models/university/person.rb#L117

**Comment by pabois** [comment]
Pas convaincu. On va avoir la même chose sur les recherches. Why ?

**Comment by pabois** [comment]
Et puis ça veut dire qu'à chaque fois qu'on ajoute un field il faut regénérer les searchs denorms
