### ISSUE TITLE
Block posts

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny#342]
- [x] l'attribut `category` doit avoir pour valeur le path complet de la category, et pas son slug uniquement
- [x] vérifier pourquoi la liste des posts a été supprimé https://github.com/noesya/communicationdemocratie-site/commit/059a376f173e1b7ef5187f0ed047b5cf9d4fa892

**Comment by alexisben** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/4630530/165730926-78af0186-f59d-456f-8bd1-726ca35c1d30.png">
