### ISSUE TITLE
Permettre l'import de fichier non images (pdf, zip...) dans les chapitres

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#347]
- [x] Désactiver le drag & drop dans les summernote des blocks
- Créer des template de blocks "Image", "Video" et "Attachment"
  - [x] Image : image
  - [x] Video : embed
  - [x] Attachment : file, cta_text

**Comment by SebouChu** [comment]
On ne peut pas utiliser has_summernote, le champ étant à l'intérieur d'un JSONB, voir comment on peut réussir à joindre le champ dans le data avec le fonctionnement de Serialization en `ActionText::Content`

**Comment by arnaudlevy** [comment]
@SebouChu est-ce que le drag and drop est désactivé ? Si oui on close l'issue
