### ISSUE TITLE
Ajouter l'option pour faire un target blank sur les boutons du block CTA

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#348]

**Comment by arnaudlevy** [comment]
J'ai fait en back il faut l'interfacer en front @sebousan

**Comment by sebousan** [comment]
@arnaudlevy c'est déjà en place.
https://github.com/noesya/osuny-hugo-theme/blob/main/layouts/partials/blocks/templates/call_to_action.html

un soucis ? 
theme peut-être pas à jour ?

**Comment by SebouChu** [comment]
Fonctionne sur thème à jour
