### ISSUE TITLE
Fiche auteur/personne non supprimée

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny#365]
- [ ] **Fiche auteur**

Il n'y a que Renaud en créateur d'actu 
https://communicationdemocratie.osuny.org/admin/communication/websites/2c9c1ff8-23a1-456e-9870-16ce3d9fd940/posts

Mais je n'ai pas que Renaud dans la team éditorial
https://www.communication-democratie.org/fr/equipe/equipe-editoriale/

On a déjà eu Alexis et Sébastien en auteur mais cela a été retiré depuis.
Donc je suppose qu'après cela devrait supprimer le fichier de l'auteur côté Osuny s'il n'a plus de post.

- [ ] **Fiche person**

Même problème pour les fiches des personnes, des utilisateurs avaient été ajouté dans un block organigramme.
Depuis retiré mais les personnes sont toujours là
https://www.communication-democratie.org/fr/equipe/

**Attention, j'ai delete manuellement les fiches en trop**

**Comment by SebouChu** [comment]
Quand on désassigne les rôles d'un user, les websites où il était présent le conserve, ils ne devraient pas

**Comment by SebouChu** [comment]
Travail ici : https://github.com/noesya/osuny/tree/rework-dependencies
