### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny#407]
**Galerie**
- [x] Ajouter la key layout à data avec en valeur :
  - [x] Grid (selected par défaut)
  - [x] Carousel
- [ ] Ajouter un champ Légende : 
Actuellement on a un champ slt et un champ texte, mais par exemple sur IUT il faudrait 3 champs (alt pour l'image, légende pour sous l'image dans la grid et texte pour le texte long dans la lightbox)

**Pages**
- [x] Mettre le premier layout en selected par défautx

**Lors du choix de blocks**
- [x] Trier par ordre alphabétique

**Comment by arnaudlevy** [comment]
J'ai refait le choix de bloc.
Pour le layout par défaut je le fais, mais d'une façon un peu troublante, après le premier save.
Pour le champ légende, je ne suis pas ok, il faut 3 champs (alt, credit, text). 
Si on a un pb de volume sur l'IUT, on truncate.
