### ISSUE TITLE
Feedbacks plateaux

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#408]
- [x] Masquer les menus qui ne sont pas utiles (liés aux universités)
- [x] Ajouter des descriptions aux blocs
- [ ] Et si on stockait le wysiwyg en markdown ?
Soit en édition visible, soit avec des boutons
- [ ] Pouvoir customiser les blocks (choisir ceux que l'on veut, définir les vignettes)

**Comment by arnaudlevy** [comment]
- [ ] Masquer les menus qui ne sont pas utiles (liés aux universités)

**Comment by arnaudlevy** [comment]
https://nuage.plateaux-numeriques.fr/s/pGgrcLXy355necM

**Comment by pabois** [comment]
Les menus sont déjà filtrés !

**Comment by pabois** [comment]
duplicate #522
