### ISSUE TITLE
Problème d'accès Osuny

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny#433]
Malgré le statut d'auteur, je n'ai pas accès à l'ajout de pages/arborescence sur Demo.Osuny et j'ai des erreurs 403 un peu partout.
(Je n'ai pas la navigation à gauche de la page)

[Page "Site web" du site exemple](https://demo.osuny.org/admin/communication/websites/c48c69c3-028f-4719-9a3c-40b40f285ed0?website_id=c48c69c3-028f-4719-9a3c-40b40f285ed0)
![scr2](https://user-images.githubusercontent.com/91660674/172392241-c873b5c6-6a9c-42a5-92bb-9a0dfc2fdec3.png)

[Page actualités du site exemple](https://demo.osuny.org/admin/communication/websites/c48c69c3-028f-4719-9a3c-40b40f285ed0/posts)
![scr1](https://user-images.githubusercontent.com/91660674/172391629-2c67e4d2-48ba-4a3c-84cb-26ed3b6228ff.png)

Au clic sur une actualité ou un dossier dans les actualités :
![scr3](https://user-images.githubusercontent.com/91660674/172392527-7a40b9ea-78ea-4ddc-9ecd-b20bb50dd153.png)
 
Par contre je peux [créer une actualité](https://demo.osuny.org/admin/communication/websites/c48c69c3-028f-4719-9a3c-40b40f285ed0/posts/new)  :
![scr4](https://user-images.githubusercontent.com/91660674/172398553-406e23e4-a4e0-4d96-a1d9-c76940cf11cf.png)

**Comment by pabois** [comment]
Yes. En fait en tant qu'auteur tu as juste accès à tes propres contenus.
Donc tu ne devrais pas voir les actus qui ne sont pas les tiennes sur le dashboard du site, et tu ne devrais pas voir le bloc permettant de modifier les catégories (ni les auteurs si vide)
