### ISSUE TITLE
Refonte blocks

### ISSUE THREAD

**Issue by pabois** [noesya/osuny#436]
- [x] Conditionnalité des blocs
- [x] Ajouter une étape de sanitization dans le setter du data des blocks
- [x] reprise de tous les blocs (edit, preview, static)
- [x] réparation des dépendances
- [x] migration des data
- [x] sanitization des blocs embed (iframe etc)

# Ajouter des descriptions (rich text) 
- [x] gallery
- [x] organization_chart
- [x] partners
- [x] files

# Suivi

- [x] call_to_action -> manque la limite à 3 ou 4 (@alexisben)
- [x] chapter
- [x] datatable -> manque le d&d des lignes (@alexisben)
- [x] definitions
- [x] embed
- [x] files
- [x] gallery
- [x] image
- [x] key_figures
- [x] organization_chart
- [x] partners
- [x] pages (main_page -> page, kind -> mode)
- [x] posts (kind -> mode)
- [x] testimonials
- [x] timeline
- [x] video

**Comment by Olivia206** [comment]
Dans le block Timeline, il y a deux champs : title et text, ce qui donne ceci :
![timeline](https://user-images.githubusercontent.com/91660674/173066309-3edaff5d-ed84-4ed4-80be-24f4b8cf93a7.png)

Est-ce qu'il pourrait être pertinent de renommer le champ "titre" par quelque chose de plus général ("événement", par exemple), pour que les utilisateurs pensent à renseigner l'année ou de carrément rajouter un autre champ de sorte à faire "année" / "titre" / "texte" (ce qui permettrait de rajouter des précisions sémantiques en front) ?

**Comment by arnaudlevy** [comment]
Oui et oui
