### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny#437]
- [x] refactor de l'embed
-> J'ai supprimé les traductions des "transcription" dans vidéo et embed et je l'ai placée dans components > text > transcription 
(j'espère que c'est clair)
- [ ] faire de la transcription un partial ? (Elle est utilisée pour les vidéos et l'intégration html)

**Comment by arnaudlevy** [comment]
C'est discutable: 
- on peut dire que c'est lié au component text, mais pas vraiment, et ce n'est pas la logique des components (types primaires)
- on peut faire un component custom, mais c'est toujours un texte
- ou on peut dupliquer les trads dans les edit
je préfère la 3e option, qui permettra d'adapter les textes aux contextes, avec des exemples
