### ISSUE TITLE
Suggestion : nouveau format des items de frise chronologique

### ISSUE THREAD

**Issue by yuna-orsini** [noesya/osuny#455]
La mise en forme quasi-carrée façon cards est difficile à lire et à utiliser.
Il serait à mon avis plus aisé de manier une liste verticale d'items - toujours avec des blocks et du drag and drop - mais un format plus horizontal et plat pour chaque item, ce qui permettrait d'allonger les input et textarea et d'avoir une vision plus globale de l'ordre des éléments.

**Comment by arnaudlevy** [comment]
C'est pas vraiment carré, ça prend la hauteur du contenu le plus haut, sauf erreur
