### ISSUE TITLE
Wishlist : la duplication de contenus

### ISSUE THREAD

**Issue by yuna-orsini** [noesya/osuny#459]
Par exemple : 
- dupliquer un bloc de contenus dans une page
- dupliquer une page
- dupliquer un bloc date dans une frise
🙃

**Comment by arnaudlevy** [comment]
J'ai fait le bloc dans la page, la page, mais pas le bloc dans une frise encore.
Et il faudrait l'option pour changer un bloc de page (sachant que c'est polymorphe)

**Comment by pabois** [comment]
duplicate #522
