### ISSUE TITLE
Quand on publie un post en définissant la date, elle n'est pas considérée

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#511]
Il faut faire en 2 fois

**Comment by pabois** [comment]
@arnaudlevy tu peux expliquer ?
Là je créé un post avec une date de publication, elle est prise en compte immédiatement

**Comment by arnaudlevy** [comment]
quand on crée un article en le publiant avec une date (en 1 fois), ça ne prend pas la date

**Comment by pabois** [comment]
Je ne reproduis toujours pas :(

**Comment by arnaudlevy** [comment]
Firefox, avant, quand la date intégrait l'heure ?
