### ISSUE TITLE
Passer en markdown ?

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#518]
Examiner Kirby
https://getkirby.com/docs/reference/text/kirbytags
https://getkirby.com/docs/reference/text/markdown

**Comment by arnaudlevy** [comment]
https://github.com/codex-team/editor.js
https://github.com/jaredreich/pell

**Comment by arnaudlevy** [comment]
https://prosemirror.net/ (utilisé par Kirby)

**Comment by pabois** [comment]
Je ne suis pas convaincu. Ca pose pas mal d'autres problèmes.
