### ISSUE TITLE
Formations : bloc actus et pages non disponible

### ISSUE THREAD

**Issue by justinpuyo** [noesya/osuny#528]
Dans le blocs de contenu d'une formation, on ne peut pas ajouter un bloc "Actualités" ou un bloc "Pages"

**Comment by arnaudlevy** [comment]
Oui parce qu'une formation peut être dans plusieurs sites

**Comment by justinpuyo** [comment]
Du coup je peux pas afficher des actus sur mes formations ?

**Comment by arnaudlevy** [comment]
mince t'as raison, c'est un cas problématique, je regarde.

**Comment by arnaudlevy** [comment]
C'est le cas maintenant !
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/
