### ISSUE TITLE
Retours Extranet

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#555]
- [x] Permettre de modifier le label du bouton "Se connecter via SSO"
- [x] Consolider les champs Twitter et LinkedIn (gérer nom d'utilisateur et URL (parsing))
- [x] Synchroniser le mail de la personne quand on update le user
- [x] Ne pas permettre une date future dans les expériences
- [x] Vérifier l'ordre des expériences
  - https://extranet.mmibordeaux.com/persons/97ceb85d-36c3-40b7-a954-5ef5362b06e9
  - https://extranet.mmibordeaux.com/persons/463d4ea7-afa2-4f4a-bd16-5de7ea863f75

**Comment by arnaudlevy** [comment]
Sur l'ordre, il faut :
- d'abord les expériences sans date de fin
- classées par date de fin, puis par date de début

**Comment by arnaudlevy** [comment]
Les champs Twitter et LinkedIn ça a l'air ok, je ne vois pas de pb :)
