### ISSUE TITLE
Ma photo a disparu

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#558]
Sur https://www.rebootcommunication.org/en-savoir-plus/qui-sommes-nous/
<img width="1410" alt="Capture d’écran 2022-11-06 à 18 22 28" src="https://user-images.githubusercontent.com/2088968/200185279-6f1d43a2-3f1d-4b0e-9bf6-d260a25c9ff7.png">

Je suis retourné sur 
https://reboot.osuny.org/admin/university/people/11b1151e-f194-458f-a805-1212acfa6dc6
il n'y avait rien, alors que j'ai une photo en tant que user.

@pabois @SebouChu ça vous parle ?

**Comment by arnaudlevy** [comment]
Je l'ai remise entre temps, donc ce n'est plus visible mais le problème n'est pas réparé pour autant.

**Comment by pabois** [comment]
Quelque part entre avril et novembre le fichier physique de l'image côté Osuny a été supprimé, mais ta fiche n'a pas été tenue à jour, d'où la disparition de l'image.
En remettant une image à la main tu as forcé le refresh, ça a réparé.
J'ai fait le test de supprimer l'image du user, ça fallback bien sur l'image du user, et ca update côté github.
Mais je n'ai pas l'explication de la suppression de l'image entre avril et novembre
