### ISSUE TITLE
Block CTA

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#569]
- [x] Mettre du drag and drop
- [x] Ne pas limiter à 3 (soit 5 ou 6, soit pas de limite)

**Comment by justinpuyo** [comment]
Je plussoie !
Peut-être aussi permettre de choisir le type (bouton ou lien) ?

**Comment by arnaudlevy** [comment]
Normalement, ça devrait être systématiquement la couleur de page (donc pas noir sur la page d'accueil, mais prune). Ce serait bien ? Ou tu as besoin de plus de latitude ? Par ailleurs on finit la nouvelle version du thème avec @alexisben et @Olivia206, ça sera comme ça les CTA : https://example.osuny.org

**Comment by justinpuyo** [comment]
@arnaudlevy couleur de la page ça me va. Je peux pas dire que j'ai "besoin" d'autres options. C'est juste que des fois on peut avoir besoin d'attirer l'attention avec un bloc qui n'est pas comme d'habitude. Peut-être aussi que le fait que j'utilise les CTA sans lien pour mettre en avant une info est un problème ? 

Le CTA du nouveau thème : ce qui me dérange c'est que le texte est plus gros que le titre. Sinon le reste c'est très bien.

**Comment by arnaudlevy** [comment]
Merci @justinpuyo ! Alors oui ça montre qu'il faut un autre type de bloc, pour mettre en avant. Et si c'était une option du chapitre ? Parce que le CTA, c'est vraiment un truc très fort, genre https://www.rebootcommunication.org

**Comment by justinpuyo** [comment]
@arnaudlevy En fait la mise en forme du CTA me convient pour ce genre de message. Mon but c'est d'interpeller genre "Arrêtez tout ! Flash info !". 
Par contre je suis preneur d'un encart moins présent. En fait j'avais pensé au champ "Notes" du bloc chapitre qui pourrait être sur fond gris clair par exemple. Mon usage ça serait pour faire un focus sur un élément dont on vient de parler, ou récapituler les infos pratiques pour un évènement, ce genre de choses.
En option du bloc chapitre c'est bien. C'est peut-être plus évident comme usage.

**Comment by justinpuyo** [comment]
@arnaudlevy est-ce qu'on peut corriger le CTA en prune sur la home en attendant le nouveau thème stp ?

**Comment by arnaudlevy** [comment]
C'est corrigé :)
