### ISSUE TITLE
Ne pas griser les boutons d'actions d'un bloc masqué

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#572]

**Comment by arnaudlevy** [comment]
Ca veut dire quoi ? Exemple ?

**Comment by alexisben** [comment]
![image](https://user-images.githubusercontent.com/4630530/211294734-8d6b8e7c-7b3d-408b-a5bc-785e5e98efb5.png)

Ça sous-entend que les boutons ne sont pas cliquables
