### ISSUE TITLE
Bloc pages : pré-remplir le titre du bloc 

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny#579]
Pré-remplir le titre du bloc par le nom de la page principale si le champ est vide.

![image](https://user-images.githubusercontent.com/4630530/204492689-e4e8b96c-11ca-44ec-a456-b13d04a65537.png)

**Comment by arnaudlevy** [comment]
Avec le nouveau système de headings, est-ce encore nécessaire ?

**Comment by arnaudlevy** [comment]
@alexisben tu en penses quoi ? Ca changeait quoi ?

**Comment by alexisben** [comment]
Je pense qu'on peut fermer ce ticket, finalement la demande n'a pas été faite par les contributeurs, et possible qu'un comportement particulier comme ça sur un seul bloc perturbe
