### ISSUE TITLE
Gérer correctement les catégories en arbre

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#621]
Hugo se comporte de façon problématique avec les taxonomies en arbre : 
- le parent ne présente pas l'article taggé avec l'enfant
- l'enfant liste les articles en double

Pour maintenir l'arbre côté Osuny (un jour, Hugo gèrera probablement) : 
- on aplatit le chemin "offre-de-formation/animation-sociale-et-socioculturelle/_index.html" -> "offre-de-formation-animation-sociale-et-socioculturelle/_index.html"
- on aplatit la mention dans les posts "offre-de-formation/animation-sociale-et-socioculturelle" -> "offre-de-formation/animation-sociale-et-socioculturelle"

**Comment by arnaudlevy** [comment]
Il n'y aura plus de parent "Offre de formation"

**Comment by arnaudlevy** [comment]
Si les users taggent explicitement "Offre de formation" on la sort, sinon, non

**Comment by arnaudlevy** [comment]
2 approches, compte-tenu de l'absence d'arbre correct.

# Tout à plat

Les fichiers de catégories sont stockés à plat et utilisent des urls plates
```
/content/categories/offre-de-formation/_index.html
/content/categories/offre-de-formation-animation-sociale-et-socioculturelle/_index.html
```

Dans les posts, on fait : 
```
categories:
  - offre-de-formation
  - offre-de-formation-animation-sociale-et-socioculturelle
```

Avec des urls comme 
```
/offre-de-formation/
/offre-de-formation-animation-sociale-et-socioculturelle/
```

# Un peu à plat mais pas complètement

Comme dans la version précédente sauf que les urls déclarées sont : 
```
/offre-de-formation/
/offre-de-formation/animation-sociale-et-socioculturelle/
```

**Comment by pabois** [comment]
Je partirais sur la version "Un peu à plat mais pas complètement".
Il me semble sain de maintenir l'existence de cette page /offre-de-formation/

Donc je fais évoluer comme ceci :
- je stocke sur github les catégories sur un seul niveau, avec un chemin flatten (/content/categories/offre-de-formation-animation-sociale-et-socioculturelle/_index.html)
- le static de catégorie à un slug trafiqué (le slug avec parentèle, donc "offre-de-formation-animation-sociale-et-socioculturelle")
- les posts contiennent des références à ces slugs trafiqués.

J'ai donc créé une méthod `slug_with_ancestors_slugs` dans le model Category. J'utilise cette méthode dans les posts. J'utilise cette méthode pour écrire le slug de la catégorie dans le fichier static de category, et j'utilise cette méthode pour calculer le git_path

**Comment by pabois** [comment]
A mon avis on pourrait prévoir pour le futur d'ajouter dans le static de la category la liste des enfants pouvoir faire des liens sur la page de catégorie.
Par exemple si je reprends tes cas la page /offre-de-formation/ aurait un lien vers sa catégorie enfant /offre-de-formation/animation-sociale-et-socioculturelle/
