### ISSUE TITLE
Permettre le tri alphabétique des tableaux (datatable block)

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#653]

**Comment by SebouChu** [comment]
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/7761386/209522878-3b4c99d5-0040-44c5-9543-f6f8363a527c.png">

Un bouton ici qui va trier automatiquement selon la 1re colonne ou alors on rajoute une ligne intermédiaire pour pouvoir trier de A à Z sur chaque colonne ?

**Comment by arnaudlevy** [comment]
Je pensais plutôt à une checkbox "trier par ordre alphabétique" comme pour les organisations et les personnes, qui maintient tout trié

**Comment by SebouChu** [comment]
Ah dac ! Je te ferai ça !

**Comment by arnaudlevy** [comment]
Merci !
