### ISSUE TITLE
Mettre le baseURL de la prod à /

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#655]
Si on met l'url du site, ça casse les tests Lighthouse.
@pabois est-ce que tu vois un problème que l'on ne verrait pas ?

**Comment by pabois** [comment]
Je ne me rappelle plus j’avais mis l’url de prod pour une raison précise que Seb avait soulevée y’a plusieurs mois. 
mais je ne me souviens plus quoi. Plan du site p-e ?

**Comment by pabois** [comment]
Ou urls de partage sociaux ?

**Comment by arnaudlevy** [comment]
Ou alors on fait une config de test ?

**Comment by pabois** [comment]
A priori on ne va pas utiliser le lighthouse de netlify.
Je trouve sain que la baseURL soit bien l'url du site.
Je close l'issue.
