### ISSUE TITLE
Toutes les pages devraient être possibles en full width ou pas

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#659]
Même la home ou les actus.

Après, on pourrait avoir un default full width pour :  
- home
- posts
- team
- ...

**Comment by pabois** [comment]
A l'heure actuelle les pages :
- index des formations
- index des diplomes
- index des actualités
- home
sont forcées en full_width, et le toggle dans l'interface n'a aucune action

Je propose qu'on revienne à un fonctionnement ou le toggle est exporté dans le static.
Les pages "spéciales" sont par défaut crées en full_width = true
(ne pas oublier de faire une migration pour repasser l'existant en full_width)
