### ISSUE TITLE
NoMethodError in Communication::Website::Category#sync_with_git_without_delay

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#674]
## Error in Osuny

**NoMethodError** in **Communication::Website::Category#sync_with_git_without_delay**
undefined method `slug_with_ancestors' for nil:NilClass

    "/#{website.special_page(:communication_posts).slug_with_ancestors}/:slug/"
                                                  ^^^^^^^^^^^^^^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/63af2cfa0ffc84000c68c1ba?event_id=63af2cf900a7ec3748000000&i=gh&m=ci)

## Stacktrace

    app/models/communication/website/permalink/category.rb:37 - pattern_in_website
    app/models/communication/website/permalink.rb:81 - pattern
    app/models/communication/website/permalink.rb:116 - published_path
    app/models/communication/website/permalink.rb:86 - computed_path
    app/models/communication/website/permalink.rb:92 - save_if_needed
    app/models/concerns/with_permalink.rb:27 - manage_permalink_in_website
    app/models/communication/website/git_file.rb:31 - sync
    app/models/concerns/with_git.rb:59 - block (2 levels) in sync_with_git
    app/models/concerns/with_git.rb:58 - each
    app/models/concerns/with_git.rb:58 - block in sync_with_git
    app/models/concerns/with_git.rb:54 - each
    app/models/concerns/with_git.rb:54 - sync_with_git
    bin/bundle:113 - load
    bin/bundle:113 - <main>

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/63af2cfa0ffc84000c68c1ba?event_id=63af2cf900a7ec3748000000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Lors de la création de catégorie dans un site qui n'a pas de posts

**Comment by arnaudlevy** [comment]
Réparé dans https://github.com/noesya/osuny/pull/690
