### ISSUE TITLE
Prévisualisation avec le thème AAA

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#677]

**Comment by alexisben** [comment]
- [ ] [Les chapitres](https://example.osuny.org/blocks/blocks-de-base/chapitres/)
- [ ] [Les images](https://example.osuny.org/blocks/blocks-de-base/image/)
- [ ] [Les vidéos](https://example.osuny.org/blocks/blocks-de-base/videos/)
- [ ] [Les tableaux](https://example.osuny.org/blocks/blocks-de-base/tableau/)
- [ ] [Les chiffre clés](https://example.osuny.org/blocks/blocks-narratifs/chiffre-cles/)
- [ ] [Les galeries](https://example.osuny.org/blocks/blocks-narratifs/galeries/)
- [ ] [Les appels à action](https://example.osuny.org/blocks/blocks-narratifs/appels-a-action/)
- [ ] [Les témoignages](https://example.osuny.org/blocks/blocks-narratifs/temoignages/)
- [ ] [Les frises](https://example.osuny.org/blocks/blocks-narratifs/frise/)
- [ ] [Les pages](https://example.osuny.org/blocks/blocks-de-liste/pages/)
- [ ] [Les actualités](https://example.osuny.org/blocks/blocks-de-liste/actualites-1/)
- [ ] [Les personnes](https://example.osuny.org/blocks/blocks-de-liste/organigramme/)
- [ ] [Les organisations](https://example.osuny.org/blocks/blocks-de-liste/partenaires/)
- [ ] [Les formations](https://example.osuny.org/blocks/blocks-de-liste/programmes/)
- [ ] [Les fichiers](https://example.osuny.org/blocks/blocks-techniques/fichiers/)
- [ ] [Les définitions](https://example.osuny.org/blocks/blocks-techniques/definitions/)
- [ ] [Les intégrations HTML](https://example.osuny.org/blocks/blocks-techniques/integration-html/)
- [ ] [Les contacts](https://example.osuny.org/blocks/blocks-techniques/contact/)
