### ISSUE TITLE
Renommer description_short en summary

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#679]
Pour clarifier pour les devs

**Comment by pabois** [comment]
Après discussion, on cherche un terme générique qui pourrait être utilisé dans tous les contextes.
Globalement c'est un texte **court**, de présentation d'objets **composites** (article, personne, organisation...).
Propositions :
- baseline
- abstract
- description_short
- description
- summary
- presentation

Finalement on retient plutôt **summary**
