### ISSUE TITLE
Erreur ?

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#696]
https://github.com/noesya/osuny/blob/8f344fd037a75c634fc517e53bc3f3bc82ed0b54/app/views/admin/communication/blocks/templates/image/_preview.html.erb#L2

@Olivia206 c'est un copier-coller Hugo qui est resté, non ?

**Comment by arnaudlevy** [comment]
@Olivia206 tu as vu ?

**Comment by Olivia206** [comment]
Est-ce que ça suffit, comme correction : [fixed errors in image preview](https://github.com/noesya/osuny/commit/1d85263c31b5ad54652e0affac360c066b3ba5c1) ?

**Comment by arnaudlevy** [comment]
Oui je crois !
