### ISSUE TITLE
La suppression de catégories ne fonctionne pas bien

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#729]
Etapes :
1. créer une catégorie "Communs"
2. créer une catégorie "PeerTube"
3. mettre "PeerTube" dans "Communs"
4. tagger un article
5. changer d'avis, sortir "PeerTube" et supprimer "Communs"

Résultat attendu : 
- pas de catégorie "Communs" ni "Communs/PeerTube"
- catégorie "PeerTube" avec l'article dedans
- lien dans l'article vers la catégorie "PeerTube"

Résultat observé : 
- 3 catégories, "PeerTube", "Communs", "Communs/PeerTube"
- apparition de "Catégories" dans le fil d'ariane
- rien dans "PeerTube"

https://www.conviviel.org/actualites/communs/peertube/
La catégorie communs n'existe plus (sauf si j'ai rangé entre temps dans git)

**Comment by pabois** [comment]
Je ne reproduis pas ça.
De mon côté après avoir testé les étapes que tu décris :
- 2 catégories, "Peertube", "Communs"
- je ne vois pas "categories" dans le fil d'ariane
- j'ai bien mon article dans "Peertube"

**Comment by pabois** [comment]
Quand on passe par la treeview ça pose des problèmes.
Corrigés par la PR #827
Par contre je ne comprends pas pourquoi l'ancienne catégorie parente supprimée n'a pas été enlevée, ni pourquoi tu as vu apparaitre "catégories" dans le fil d'ariane
