### ISSUE TITLE
Supprimer les trix-content

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#743]
- [x] Passer sur la branche de Summernote-Rails avec uniquement le cleaner
- [x] Garder `has_summernote` uniquement sur les attributs qui le nécessitent
- [x] Ne plus dépendre des legacy attributes (`Communication::Website::Page#text`, `Communication::Website::Post#text`)
  - [x] Gérer l'import WordPress
- [x] Supprimer les mentions aux summernote_embeds
- [x] Vérifier l'utilisation de méthodes d'ActionText appelées sur les attributs définis comme Summernote (ex: `to_html`)

**Comment by arnaudlevy** [comment]
Et les divs en cascade

https://github.com/noesya/bordeauxmontaigne-iut/blob/main/content/fr/programs/carrieres-sociales/animation-sociale-et-socioculturelle-app-fc/_index.html#L52

```
accessibility: >
  <div>   <div>   <div>   <div>   <div>   <div>   <div>   <div>   <div>   <div>   <div>   <div>   <div>   <p>L'ensemble des locaux est accessible. De nombreux aménagements ont  été réalisés afin de faciliter l'accès des étudiants en situation de  handicap moteur dans l'université. Il en va de même pour les équipements  sanitaires. <br></p> <p>Le Pôle Handicap de l'Université Bordeaux  Montaigne a pour mission d'accueillir et d'accompagner dans leurs études  les étudiants en situation de handicap.<br>Il assure ainsi le suivi des  étudiants qui rencontrent des besoins spécifiques permanents, liés à un  handicap ou à une maladie invalidante.</p> <p>Ses actions tournent  autour de trois grands axes : préparer l'arrivée à l'université des  élèves handicapés en relation avec les personnes ressources de  l'enseignement secondaire, accueillir et accompagner les étudiants  handicapés tout au long de leur parcours universitaire, préparer avec  eux leur insertion professionnelle.<br><br>Plus d'informations sur le site de l'université  →  <a href="https://etu.u-bordeaux-montaigne.fr/fr/etudes-et-scolarite/handicap.html">Handicap</a></p> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>
```

**Comment by arnaudlevy** [comment]
j’enregistre ici 
https://bordeauxmontaigne.osuny.org/admin/university/organizations/d4360a4a-2515-47d1-96b9-fe3877d033ae/edit 
et ça garde tous les div avec trix-content, ça nettoie rien du tout

```
<div class="trix-content">
  <div class="trix-content">
  
</div>
</div>
```

**Comment by arnaudlevy** [comment]
Et ce fichier là devrait pas être supprimé ?
<img width="311" alt="image" src="https://user-images.githubusercontent.com/2088968/219474557-e5518320-c957-4098-80dd-d117601c07a4.png">

**Comment by SebouChu** [comment]
Sûrement

**Comment by arnaudlevy** [comment]
et le blob juste dessous aussi je pense

**Comment by arnaudlevy** [comment]
Bravo !!!
