### ISSUE TITLE
Absence de titre de page pour la double authentification

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny#760]
Sur la page de double authentification, le titre de la page correspond à son url, ce qui n'est pas conforme aux bonnes pratiques et pose un problème d'accessibilité :

<img width="582" alt="Capture d’écran 2023-01-24 à 11 25 40" src="https://user-images.githubusercontent.com/91660674/214267969-ead1db82-9d54-491c-a448-2fc062ab668a.png">

**Comment by arnaudlevy** [comment]
Ca concerne toutes les pages devise je crois
