### ISSUE TITLE
Couleur du texte en sélection (`::selection`) dans le footer

### ISSUE THREAD

**Issue by MatteoGauthier** [noesya/osuny#770]
Lors de la sélection de texte, la couleur de fond (`background-color`) à la valeur `rgba(0,0,0,.7)`, lorsqu'un texte est sélectionné au niveau de la section footer la sélection n'est pas visible

https://user-images.githubusercontent.com/32040951/215071065-ad1e5d09-8bee-48f4-b74a-f05185deb833.mp4

**Comment by arnaudlevy** [comment]
Merci !
