### ISSUE TITLE
URI::InvalidURIError in admin/communication/websites/posts#update

### ISSUE THREAD

**Issue by SebouChu** [noesya/osuny#785]
## Error in Osuny

**URI::InvalidURIError** in **admin/communication/websites/posts#update**
bad URI(is not URI?): "/photos/[object Object]"

[View on Bugsnag](https://app.bugsnag.com/noesya-1/osuny/errors/63db90e541331a00086b606b?event_id=63db90e500ad1857d6920000&i=gh&m=ci)

## Stacktrace

    app/models/concerns/with_featured_image.rb:33 - photo_import_unsplash
    app/models/concerns/with_featured_image.rb:28 - add_photo_import
    app/controllers/admin/communication/websites/posts_controller.rb:72 - update
    app/controllers/application_controller/with_locale.rb:19 - switch_locale

[View full stacktrace](https://app.bugsnag.com/noesya-1/osuny/errors/63db90e541331a00086b606b?event_id=63db90e500ad1857d6920000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by arnaudlevy** [comment]
Pb à l'initialisation du search pexels / unsplash
