### ISSUE TITLE
Signaler les éléments non publiés

### ISSUE THREAD

**Issue by justinpuyo** [noesya/osuny#787]
Que ce soit pour les formations ou les pages, on ne distingue pas les éléments non publiés.
Dans une version précédentes ils étaient grisés, mais j'imagine que c'est gênant pour l'accessibilité.
On pourrait peut-être ajouter une étiquette "non publié" tout simplement ?

**Comment by arnaudlevy** [comment]
Normalement c'est remis, c'était juste une erreur

**Comment by arnaudlevy** [comment]
Ah j'ai pas checké pour les formations
