### ISSUE TITLE
Bloc Organisations - ouvrir les liens dans une nouvelle fenêtre

### ISSUE THREAD

**Issue by MagaliAngles** [noesya/osuny#848]
Dans le BO, il manque la possibilité d'ouvrir les liens externes dans une nouvelle fenêtre, comme pour le bloc CTA
<img width="877" alt="Capture d’écran 2023-02-20 à 12 10 12" src="https://user-images.githubusercontent.com/108729992/220089390-4bf461bc-be88-48f4-82a6-dc9234bc1887.png">

**Comment by arnaudlevy** [comment]
Ça devrait être toujours le cas, d'une part, et d'autre part on ne ferait pas mieux de faire une vraie organisation ?

**Comment by MagaliAngles** [comment]
yes, on a créé aujd les organisations dans le tableau de bord

**Comment by arnaudlevy** [comment]
@alexisben quand c'est pas une vraie orga, possible de mettre des target blank ?

**Comment by alexisben** [comment]
https://github.com/noesya/osuny-hugo-theme-aaa/commit/bce3865b2993c2cbc4ac32f774829f2da5b513ab
