### ISSUE TITLE
l'action publish du website::post_controller appelle sync_objects_with_git qui ne devrait pas exister

### ISSUE THREAD

**Issue by pabois** [noesya/osuny#850]
Cette méthode n'est appelée qu'ici et ne devrait pas exister

**Comment by arnaudlevy** [comment]
Supprimer aussi 
```
  def has_website_for_self?(website)
    websites_for_self.include?(website)
  end
```
https://github.com/noesya/osuny/blob/be94aa7e83a71ebf874e771c53a7fca30bd82ef4/app/models/concerns/with_git.rb#L76

**Comment by SebouChu** [comment]
Sera géré dans #833
