### ISSUE TITLE
[Actualités] cadrage image

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#886]

**Comment by arnaudlevy** [comment]
https://adherents.ran-coper.fr les images doivent avoir le même ratio

**Comment by alexisben** [comment]
Cropper les images au même format sur l'index des actu

**Comment by alexisben** [comment]
https://github.com/noesya/osuny/pull/905

**Comment by alexisben** [comment]
On a fixe en CSS, pas trouvé comment avec kamifusen direct

**Comment by arnaudlevy** [comment]
https://github.com/noesya/kamifusen/issues/4
En fait il faudrait reprendre le DSL, il est trop étrange
