### ISSUE TITLE
[Actualités] Intégrer les blocs correctement

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#892]

**Comment by alexisben** [comment]
Manque les blocs de liste, et un bug de js sur les sliders

**Comment by alexisben** [comment]
Intégrer layout map pour le block Organisations

**Comment by alexisben** [comment]
- [ ] Vérifier les blocs actualités

**Comment by pabois** [comment]
en lien avec #1140 (code partagé)
