### ISSUE TITLE
Nouvel éditeur de contenu

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny#973]
Avantages :
- [ ] Retrouver facilement son bloc (savoir ce qu'il y a dedans)
- [ ] Gérer le plan du document facilement
- [ ] Créer des hiérarchies, au delà d'un seul niveau de titre
- [ ] Simplifier l'édition différente pour une page et ses blocs (confusant)
- [ ] Gérer les documents longs plus facilement

En bonus : 
- [ ] la création d'un bloc vide est parfois troublante, si on ne l'enregistre pas on s'attendrait à ce qu'il ne se crée pas. Peut-être un bouton "annuler" ?

**Comment by arnaudlevy** [comment]
@justinpuyo aimerait bien en disposer pour fin avril, afin de faire les formations directement dessus

**Comment by arnaudlevy** [comment]
Et Renaud trouve Pure beaucoup plus beau qu'Appstack, on dirait quasiment un site en front

**Comment by alexisben** [comment]
Workflow pour la mise à jour des sites : 

Pour chaque site :
- Depuis l'admin / console : lancer la mise à jour des données pour chaque site (déplacement des titres des blocks dans les headings)
- Mise à jour du thème en local
- Vérification local du thème
- Déploiement de la mise à jour du thème sur le site en prod
- Vérification du site en prod
