### ISSUE TITLE
La route `/users/edit` renvoie une erreur HTTP 500

### ISSUE THREAD

**Issue by MatteoGauthier** [noesya/osuny#984]
Problème apparu sur l'URL suivante : https://bordeauxmontaigne.osuny.org/users/edit

**Comment by arnaudlevy** [comment]
Merci !
Tu as trouvé ce lien où stp ?

**Comment by arnaudlevy** [comment]
@pabois je crois que c'est lié aux droits de responsable de site Web

**Comment by MatteoGauthier** [comment]
> Merci ! Tu as trouvé ce lien où stp ?

Dans la navbar, sur le lien vers le profile


https://user-images.githubusercontent.com/32040951/228828957-fb4402c7-5415-49d5-9196-70e250d6bf3d.mov
