### ISSUE TITLE
Remarque et proposition - UX de l'écran de vérification SMS / Email

### ISSUE THREAD

**Issue by MatteoGauthier** [noesya/osuny#991]
Bonjour, j'ai quelques remarques sur l'expérience utilisateur de l'écran de vérification qui apparait après l'authentification classique de l'utilisateur.

URL en question : `https://xxx.osuny.org/users/two_factor_authentication`

## Remarques

- Il manque des informations sur la nature de la page en question, en l'occurrence le processus de vérification par SMS n'est pas énoncé
- Les éléments d'actions sont trop proches et peuvent causer des erreurs d'interactions avec les boutons
- Les boutons "Submit" et "Sign Out" ont tous les deux une couleurs vives, une couleur aurait été préférable. De plus, le bouton d'action principale est situé sur la droite, ce qui n'est généralement pas commun.

### Sources

- https://balsamiq.com/learn/articles/button-design-best-practices/
- https://lawsofux.com/hicks-law/
- https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150

![Case study UX - Verification Screen](https://user-images.githubusercontent.com/32040951/230324225-2e8cd706-45b4-4120-9fc5-15c9cfbc4fb3.png)

## Proposition de modification

| Mobile | Desktop |
|--------|--------|
| ![Verification Screen Redesign - Mobile](https://user-images.githubusercontent.com/32040951/230324319-90504e35-39c6-4127-a2a6-f50536fd3578.png) | ![Verification Screen Redesign - Desktop](https://user-images.githubusercontent.com/32040951/230324322-5887551c-7b17-40ec-9f84-11c7ece80bd5.png) | 

Il est important pour moi de souligner que je ne cherche pas à dévaloriser le travail accompli sur cette page, mais plutôt à apporter une contribution au projet.

Bonne journée

**Comment by arnaudlevy** [comment]
Merci @MatteoGauthier trop cool ton issue !!!

**Comment by SebouChu** [comment]
Merci beaucoup @MatteoGauthier pour ton retour !

La page n'est pas vraiment une vérification de téléphone, mais une vérification d'identité. Donc on aurait plus quelque chose du style "Verify your identity with a code".

Sinon c'est top, et je suis bien d'accord avec toi sur le placement des boutons 😉

**Comment by arnaudlevy** [comment]
@MatteoGauthier Est-ce que c'est mieux comme ça ?

**Comment by MatteoGauthier** [comment]
> Merci beaucoup @MatteoGauthier pour ton retour !
> 
> La page n'est pas vraiment une vérification de téléphone, mais une vérification d'identité. Donc on aurait plus quelque chose du style "Verify your identity with a code".
> 
> Sinon c'est top, et je suis bien d'accord avec toi sur le placement des boutons 😉

@SebouChu Avec plaisir ! J'avais un doute sur l'appelation du processus de vérification, "multi-factor authentication" convient effectivement mieux 👍

**Comment by MatteoGauthier** [comment]
> @MatteoGauthier Est-ce que c'est mieux comme ça ?

À vous d'en juger, mais ça me semble très bien 😃

**Comment by arnaudlevy** [comment]
Merci encore, je close !
